### ISSUE TITLE
Code 5: dyld: Library not loaded

### ISSUE THREAD

**Issue by vdesabou** [akaralar/SafariHistorySearch#1]
Hello,

I wanted to test your workflow but I get:

```
Starting debug for 'Safari History Search'

[2016-04-28 17:26:18][ERROR: input.scriptfilter] Code 5: dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/vdesabou/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.7D7BF4ED-49EF-429A-AE02-C09CCAAC77A6/./safariSearch
  Reason: image not found
```

Is there anything I can do to workaround this?
Thanks

**Comment by akaralar** [comment]
@vdesabou can you elaborate a bit more on what you did and what happened?

**Comment by vdesabou** [comment]
Yes I'm simply trying to use the workflow by invoking `shs test`

Looks like this error happens when there is a signature issue for the program(I quickly googled it). When I invoke ./safariSearch in terminal, I get the same error.

**Comment by akaralar** [comment]
I don't sign the binary, I export it using `xcrun -sdk macosx swiftc -O SafariSearch.swift -o SafariSearch` . Can you run this command in the repo and run the resulting binary with `./SafariSearch "<search terms>"` and see if it works in the command line?

I also pushed a new version and added the hashbang(`#!/usr/bin/env xcrun swift`) on the top of the script. Maybe that was causing the error?

**Comment by vdesabou** [comment]
> Can you run this command in the repo and run the resulting binary with ./SafariSearch "<search terms>" and see if it works in the command line?

I get:

```
 10:48:50  vdesabou@MacBookPro-Vincent  ~/Downloads/SafariHistorySearch-master 
$ ./safariSearch test
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/vdesabou/Downloads/SafariHistorySearch-master/./safariSearch
  Reason: image not found
[1]    78541 trace trap  ./safariSearch test
```

I have no experience at all with SWIFT and I dot have Xcode installed on my machine. 

While googling I found this: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2648 maybe ?

**Comment by akaralar** [comment]
Yeah I think they are somewhat relevant, the reason is the binary doesn't come with the swift library. I'm working on a fix and will let you know when it is ready. Thanks!

**Comment by akaralar** [comment]
@vdesabou hey, sorry for this taking so long but can you check whether it's working for you now?

**Comment by vdesabou** [comment]
Hello,

Yes I can confirm it is working now with latest release ! Thanks

**Comment by akaralar** [comment]
@vdesabou you're welcome, closing this
